package app.spanishstudy.vot;

import android.app.Activity;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;import app.morphe.extension.youtube.patches.voiceovertranslation.TranscriptSegment;
final class SpanishSubtitleOverlay {
 private static Activity activity;private static TextView textView;private static List<TranscriptSegment> segments=new ArrayList<>();private static int cursor;private SpanishSubtitleOverlay(){}
 static void setSegments(List<TranscriptSegment> snapshot){segments=snapshot==null?new ArrayList<>():new ArrayList<>(snapshot);cursor=0;}
 static void update(Activity a,long timeMs){if(a==null||a.isFinishing()||a.isDestroyed())return;if(!SpanishStudyPrefs.showSubtitles(a)){hide();return;}ensureAttached(a);TranscriptSegment active=find(timeMs);if(active==null||active.text==null||active.text.isBlank()){textView.setVisibility(View.GONE);return;}String lang=active.lang==null?"":active.lang.toLowerCase();if(!lang.startsWith("es")){textView.setVisibility(View.GONE);return;}if(!active.text.contentEquals(textView.getText()))textView.setText(active.text);textView.setVisibility(View.VISIBLE);}
 static void hide(){if(textView!=null)textView.setVisibility(View.GONE);}
 private static TranscriptSegment find(long timeMs){List<TranscriptSegment> local=segments;if(local.isEmpty())return null;if(cursor>=local.size())cursor=local.size()-1;while(cursor>0&&timeMs<local.get(cursor).playbackStartMs)cursor--;while(cursor+1<local.size()&&timeMs>=local.get(cursor).playbackEndMs)cursor++;TranscriptSegment s=local.get(cursor);return timeMs>=s.playbackStartMs&&timeMs<s.playbackEndMs?s:null;}
 private static void ensureAttached(Activity a){if(textView!=null&&activity==a&&textView.getParent()!=null)return;if(textView!=null&&textView.getParent() instanceof ViewGroup)((ViewGroup)textView.getParent()).removeView(textView);activity=a;textView=new TextView(a);textView.setTextColor(Color.WHITE);textView.setTextSize(18);textView.setTypeface(Typeface.DEFAULT,Typeface.BOLD);textView.setGravity(Gravity.CENTER);int ph=dp(a,12),pv=dp(a,7);textView.setPadding(ph,pv,ph,pv);GradientDrawable bg=new GradientDrawable();bg.setColor(0xCC000000);bg.setCornerRadius(dp(a,8));textView.setBackground(bg);textView.setElevation(dp(a,8));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT,Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);lp.leftMargin=dp(a,20);lp.rightMargin=dp(a,20);lp.bottomMargin=dp(a,92);a.addContentView(textView,lp);textView.setVisibility(View.GONE);}
 private static int dp(Activity a,int v){return Math.round(v*a.getResources().getDisplayMetrics().density);}
}
