package app.spanishstudy.vot;

import android.content.*;import android.net.Uri;import android.provider.MediaStore;import org.json.*;import java.io.OutputStream;import java.nio.charset.StandardCharsets;import java.util.*;
final class VocabularyExporter {private VocabularyExporter(){}
 static Uri exportCsv(Context c,String videoId,List<VocabularyEntry> es)throws Exception{StringBuilder o=new StringBuilder("spanish,count,difficulty,first_timestamp,example_1,example_2,spanishdict_url,status\n");for(VocabularyEntry e:es){List<String>x=e.getExamples();o.append(csv(e.word)).append(',').append(e.count).append(',').append(String.format(Locale.ROOT,"%.2f",e.difficultyScore)).append(',').append(csv(VocabularyAnalyzer.timestamp(e.firstTimestampMs))).append(',').append(csv(x.size()>0?x.get(0):"")).append(',').append(csv(x.size()>1?x.get(1):"")).append(',').append(csv("https://www.spanishdict.com/translate/"+Uri.encode(e.word))).append(',').append(csv("learning")).append('\n');}return writeDownload(c,fileBase(videoId)+".csv","text/csv",o.toString());}
 static Uri exportJson(Context c,String videoId,List<VocabularyEntry> es)throws Exception{JSONArray a=new JSONArray();for(VocabularyEntry e:es){JSONObject j=new JSONObject();j.put("spanish",e.word);j.put("count",e.count);j.put("difficulty",e.difficultyScore);j.put("first_timestamp_ms",e.firstTimestampMs);j.put("first_timestamp",VocabularyAnalyzer.timestamp(e.firstTimestampMs));j.put("examples",new JSONArray(e.getExamples()));j.put("spanishdict_url","https://www.spanishdict.com/translate/"+Uri.encode(e.word));a.put(j);}JSONObject r=new JSONObject();r.put("video_id",videoId==null?"":videoId);r.put("words",a);return writeDownload(c,fileBase(videoId)+".json","application/json",r.toString(2));}
 static Uri exportAnkiTsv(Context c,String videoId,List<VocabularyEntry> es)throws Exception{StringBuilder o=new StringBuilder("Spanish\tContext\tTimestamp\tSpanishDict\n");for(VocabularyEntry e:es){String x=e.getExamples().isEmpty()?"":e.getExamples().get(0);o.append(tsv(e.word)).append('\t').append(tsv(x)).append('\t').append(tsv(VocabularyAnalyzer.timestamp(e.firstTimestampMs))).append('\t').append(tsv("https://www.spanishdict.com/translate/"+Uri.encode(e.word))).append('\n');}return writeDownload(c,fileBase(videoId)+"_anki.tsv","text/tab-separated-values",o.toString());}
 private static Uri writeDownload(Context c,String n,String m,String t)throws Exception{ContentResolver r=c.getContentResolver();ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,n);v.put(MediaStore.Downloads.MIME_TYPE,m);v.put(MediaStore.Downloads.RELATIVE_PATH,"Download/SpanishStudyVOT");Uri u=r.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IllegalStateException("Could not create Downloads entry");try(OutputStream os=r.openOutputStream(u)){if(os==null)throw new IllegalStateException("Could not open export stream");os.write(t.getBytes(StandardCharsets.UTF_8));}return u;}
 private static String fileBase(String id){String s=id==null?"video":id.replaceAll("[^A-Za-z0-9_-]","_");return"spanish_vocab_"+(s.isBlank()?"video":s);}private static String csv(String s){String v=s==null?"":s.replace("\"","\"\"");return"\""+v+"\"";}private static String tsv(String s){return s==null?"":s.replace('\t',' ').replace('\n',' ').replace('\r',' ');}}
