package app.spanishstudy.vot;

import android.app.*;import android.content.Intent;import android.graphics.Typeface;import android.net.Uri;import android.view.*;import android.widget.*;import java.util.*;import app.morphe.extension.youtube.patches.voiceovertranslation.VoiceOverTranslationPatch;
final class VocabularyReviewDialog {private VocabularyReviewDialog(){}
 static void show(Activity a,String videoId,List<VocabularyEntry> es){if(a==null||a.isFinishing())return;LinearLayout root=new LinearLayout(a);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(a,12),dp(a,8),dp(a,12),dp(a,8));TextView info=new TextView(a);info.setText("Ranked likely-tricky words. Listen uses the same Spanish voice as the dub. Marking Known removes a word from future reviews.");info.setTextSize(14);info.setPadding(0,0,0,dp(a,8));root.addView(info);LinearLayout actions=new LinearLayout(a);actions.setOrientation(LinearLayout.HORIZONTAL);Button csv=button(a,"CSV"),json=button(a,"JSON"),anki=button(a,"Anki TSV");actions.addView(csv);actions.addView(json);actions.addView(anki);root.addView(actions);ScrollView scroll=new ScrollView(a);LinearLayout list=new LinearLayout(a);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1f));for(VocabularyEntry e:es)addEntryRow(a,list,e);csv.setOnClickListener(v->export(a,()->VocabularyExporter.exportCsv(a,videoId,remainingEntries(a,es))));json.setOnClickListener(v->export(a,()->VocabularyExporter.exportJson(a,videoId,remainingEntries(a,es))));anki.setOnClickListener(v->export(a,()->VocabularyExporter.exportAnkiTsv(a,videoId,remainingEntries(a,es))));new AlertDialog.Builder(a).setTitle("Spanish vocabulary preview ("+es.size()+")").setView(root).setNegativeButton("Close",null).show();}
 private static void addEntryRow(Activity a,LinearLayout list,VocabularyEntry e){LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,dp(a,5),0,dp(a,5));TextView text=new TextView(a);String ex=e.getExamples().isEmpty()?"":"\n"+e.getExamples().get(0);text.setText(e.word+"  ×"+e.count+"  · "+VocabularyAnalyzer.timestamp(e.firstTimestampMs)+ex);text.setTextSize(15);text.setTypeface(Typeface.DEFAULT,Typeface.NORMAL);row.addView(text,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1f));Button listen=button(a,"Listen");listen.setOnClickListener(v->VoiceOverTranslationPatch.speakPreviewText(e.word));row.addView(listen);Button lookup=button(a,"Lookup");lookup.setOnClickListener(v->{try{a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.spanishdict.com/translate/"+Uri.encode(e.word))));}catch(Exception x){Toast.makeText(a,"Could not open dictionary",Toast.LENGTH_SHORT).show();}});row.addView(lookup);CheckBox known=new CheckBox(a);known.setText("Known");known.setChecked(SpanishStudyPrefs.isKnown(a,e.word));known.setOnCheckedChangeListener((b,c)->SpanishStudyPrefs.setKnown(a,e.word,c));row.addView(known);list.addView(row);View d=new View(a);d.setBackgroundColor(0x33000000);list.addView(d,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(a,1)));}
 private static List<VocabularyEntry> remainingEntries(Activity a,List<VocabularyEntry> es){List<VocabularyEntry> r=new ArrayList<>();for(VocabularyEntry e:es)if(!SpanishStudyPrefs.isKnown(a,e.word))r.add(e);return r;}
 private interface Exporter{Uri run()throws Exception;}private static void export(Activity a,Exporter e){try{e.run();Toast.makeText(a,"Saved to Downloads/SpanishStudyVOT",Toast.LENGTH_LONG).show();}catch(Exception x){Toast.makeText(a,"Export failed: "+x.getMessage(),Toast.LENGTH_LONG).show();}}
 private static Button button(Activity a,String l){Button b=new Button(a);b.setText(l);b.setAllCaps(false);b.setMinWidth(0);return b;}private static int dp(Activity a,int v){return Math.round(v*a.getResources().getDisplayMetrics().density);}}
